export const SET_SIGNIN_USER_INFO = 'SET_SIGNIN_USER_INFO';
export const SET_PROFILE_INFO = 'SET_PROFILE_INFO';

export const SET_CART_INFO = 'SET_CART_INFO';
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SET_STATUSBAR_HEIGHT = 'SET_STATUSBAR_HEIGHT';
export const SET_CURRENT_ADDRESS_STATUS = 'SET_CURRENT_ADDRESS_STATUS';
export const SET_DELETE_ADDRESS_FLAG = 'SET_DELETE_ADDRESS_FLAG';
export const SET_CART_RESTAURANT_NOTE = 'SET_CART_RESTAURANT_NOTE';